/** Iconos disponibles. Sus dibujos están en dibujos.ts. */
export const NOMBRES_DE_ICONO = [
  'cursor',
  'reproducir',
  'pausa',
  'detener',
  'bucle',
  'escuchar',
  'silencio',
  'pista',
  'cerrar',
  'atras',
  'adelante',
  'candado',
  'acierto',
  'fallo',
  'mapa',
  'repaso',
  'repertorio',
  'glosario',
  'ajustes',
  'metronomo',
  'lapiz',
  'goma',
  'mas',
  'menos',
  'descargar',
  'nota',
  'estrella',
  'pianoroll',
  'subir',
  'bajar',
  'deshacer',
  'rehacer',
  'papelera',
  'pentagrama',
  'llama',
  'cargar',
  'puntero',
] as const

export type NombreDeIcono = (typeof NOMBRES_DE_ICONO)[number]
